version: '3.8'
services:
  "backend-application":
    build: "./backend-application"
    ports:
      - "8080:8080"
    volumes:
      - "./backend-application/src:/backend-application/src"
    depends_on:
      - mongo-db
  mongo-db:
    build: ./mongo-db
    image: mongo:latest
    ports:
       - "27017:27017"
    environment:
       MONGO_DB: mongodb
       MONGODB_PASSWORD: abc12
 
    
